// doc-catalog/web/src/components/FieldCard.tsx
import { useEffect, useRef, useState } from "react";
import { Link } from "react-router-dom";
import { Eye, EyeOff, Copy, Check, FileText, ExternalLink } from "lucide-react";
import { Card } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Tooltip, TooltipContent, TooltipTrigger } from "@/components/ui/tooltip";
import { cn } from "@/lib/utils";
import { revealField } from "@/api";
import type { VaultField, DocField } from "@/api";

// field: minimal shape both VaultField and per-doc DocField satisfy.
export function FieldCard({ field }: { field: VaultField | DocField }) {
  const [revealed, setRevealed] = useState<string | null>(null);
  const [copied, setCopied] = useState(false);
  const [busy, setBusy] = useState(false);
  const timer = useRef<ReturnType<typeof setTimeout>>();

  useEffect(() => () => clearTimeout(timer.current), []);

  async function value(): Promise<string> {
    if (revealed == null) {
      const v = await revealField(field.id);
      setRevealed(v);
      return v;
    }
    return revealed;
  }

  function remask() {
    setRevealed(null);
    clearTimeout(timer.current);
  }

  async function toggleReveal() {
    if (revealed != null) {
      remask();
      return;
    }
    setBusy(true);
    try {
      await value();
      clearTimeout(timer.current);
      timer.current = setTimeout(remask, 15000);
    } finally {
      setBusy(false);
    }
  }

  async function copy() {
    setBusy(true);
    try {
      const v = await value();
      await navigator.clipboard.writeText(v);
      setCopied(true);
      setTimeout(() => setCopied(false), 1400);
      clearTimeout(timer.current);
      timer.current = setTimeout(remask, 15000);
    } finally {
      setBusy(false);
    }
  }

  const shown = revealed != null;
  const expired = !!field.expiry && new Date(field.expiry) < new Date();
  const count = "doc_count" in field ? (field.doc_count ?? 0) : 0;
  const documentId = "document_id" in field ? field.document_id : undefined;
  const srcHref =
    count === 1
      ? `/doc/${documentId}`
      : `/library?field=${field.id}&label=${encodeURIComponent(field.label ?? "")}`;

  return (
    <Card
      className={cn(
        "gap-2 p-4 transition-shadow",
        shown && "border-vault/40 shadow-md",
        expired && "opacity-60",
      )}
    >
      <div className="flex items-baseline justify-between gap-2">
        <span className="mono text-xs font-medium uppercase tracking-wide text-muted-foreground">
          {field.label}
        </span>
        {field.expiry && (
          <span className={cn("mono text-[11px] tracking-wide text-muted-foreground/70", expired && "text-danger")}>
            {expired ? "expired" : "exp"} · {field.expiry}
          </span>
        )}
      </div>

      <div className="mt-1 flex items-center gap-2">
        <button
          type="button"
          onClick={toggleReveal}
          disabled={busy}
          title={shown ? "Hide" : "Reveal"}
          className={cn(
            "mono flex h-10 min-w-0 flex-1 items-center overflow-hidden rounded-md px-3 text-left text-sm tracking-[0.14em] text-foreground transition-colors",
            "bg-foreground/[0.06] bg-[repeating-linear-gradient(-45deg,transparent_0_6px,color-mix(in_srgb,var(--foreground)_5%,transparent)_6px_12px)] hover:bg-foreground/[0.09]",
            shown && "bg-vault-wash bg-none text-vault tracking-[0.04em] shadow-[inset_0_-2px_0_var(--vault)]",
          )}
        >
          <span className="truncate">{revealed ?? field.value_masked}</span>
        </button>
        <div className="flex flex-none gap-1.5">
          <Tooltip>
            <TooltipTrigger asChild>
              <Button
                variant="outline"
                size="icon"
                onClick={toggleReveal}
                disabled={busy}
                aria-label={shown ? "Hide value" : "Reveal value"}
              >
                {shown ? <EyeOff /> : <Eye />}
              </Button>
            </TooltipTrigger>
            <TooltipContent>{shown ? "Hides again in 15s" : "Reveal (auto-hides in 15s)"}</TooltipContent>
          </Tooltip>
          <Button
            variant="outline"
            size="icon"
            onClick={copy}
            disabled={busy}
            aria-label="Copy value"
            className={cn(copied && "border-vault text-vault bg-vault-wash")}
          >
            {copied ? <Check /> : <Copy />}
          </Button>
        </div>
      </div>

      {count > 0 && (
        <Link
          to={srcHref}
          className="mono mt-1 inline-flex items-center gap-1.5 text-[11px] text-muted-foreground hover:text-accent"
        >
          {count === 1 ? <FileText className="size-3.5" /> : <ExternalLink className="size-3.5" />}
          {count === 1 ? "View source" : `${count} documents`}
        </Link>
      )}
    </Card>
  );
}

// doc-catalog/web/src/lib/FieldCard.svelte
<script>
  import { revealField } from '$lib/api.js';
  import Icon from '$lib/Icon.svelte';

  // field: { id, label, value_masked, entity_class, expiry }
  let { field } = $props();

  let revealed = $state(null);   // plaintext once fetched, else null (masked)
  let copied = $state(false);
  let busy = $state(false);
  let timer;

  async function value() {
    if (revealed == null) revealed = await revealField(field.id);
    return revealed;
  }
  async function toggleReveal() {
    if (revealed != null) { remask(); return; }
    busy = true;
    try { await value(); clearTimeout(timer); timer = setTimeout(remask, 15000); }
    finally { busy = false; }
  }
  function remask() { revealed = null; clearTimeout(timer); }
  async function copy() {
    busy = true;
    try {
      await navigator.clipboard.writeText(await value());
      copied = true; setTimeout(() => (copied = false), 1400);
      clearTimeout(timer); timer = setTimeout(remask, 15000);
    } finally { busy = false; }
  }

  const shown = $derived(revealed != null);
  const expired = $derived(field.expiry && new Date(field.expiry) < new Date());

  // Trace back to the document(s) this value was extracted from. One source →
  // straight to the doc; several → the Library filtered to just those docs (the
  // opaque field id goes in the URL, never the plaintext value).
  const count = $derived(field.doc_count ?? 0);
  const srcHref = $derived(
    count === 1
      ? `/doc/${field.document_id}`
      : `/library?field=${field.id}&label=${encodeURIComponent(field.label ?? '')}`
  );
</script>

<div class="field card" class:expired class:live={shown}>
  <div class="row">
    <span class="label mono">{field.label}</span>
    {#if field.expiry}
      <span class="exp mono" class:warn={expired}>
        {expired ? 'expired' : 'exp'} · {field.expiry}
      </span>
    {/if}
  </div>

  <div class="valrow">
    <button class="val mono" class:on={shown} onclick={toggleReveal}
            title={shown ? 'Hide' : 'Reveal'} disabled={busy}>
      <span class="txt">{revealed ?? field.value_masked}</span>
    </button>
    <div class="acts">
      <button class="ic" onclick={toggleReveal} disabled={busy}
              aria-label={shown ? 'Hide value' : 'Reveal value'}>
        <Icon name={shown ? 'eye-off' : 'eye'} size="17px" />
      </button>
      <button class="ic copy" class:done={copied} onclick={copy} disabled={busy} aria-label="Copy value">
        <Icon name={copied ? 'check' : 'copy'} size="16px" />
      </button>
    </div>
  </div>

  {#if count > 0}
    <a class="src mono" href={srcHref}>
      <Icon name={count === 1 ? 'file-text' : 'external-link'} size="13px" />
      {count === 1 ? 'View source' : `${count} documents`}
    </a>
  {/if}
</div>

<style>
  .field { padding: 13px 14px 14px; transition: border-color .18s ease, box-shadow .18s ease; }
  .field.live { border-color: color-mix(in srgb, var(--teal) 40%, var(--line)); box-shadow: var(--shadow-lg); }
  .field.expired { opacity: 0.6; }

  .row { display: flex; align-items: baseline; justify-content: space-between; gap: 8px; }
  .label {
    font-size: var(--t-cap); text-transform: uppercase; letter-spacing: 0.09em;
    color: var(--muted); font-weight: 500;
  }
  .exp { font-size: 0.625rem; color: var(--faint); letter-spacing: 0.04em; }
  .exp.warn { color: var(--stamp); }

  .valrow { display: flex; align-items: center; gap: 8px; margin-top: 11px; }

  .src {
    display: inline-flex; align-items: center; gap: 5px; margin-top: 10px;
    font-size: 0.6875rem; color: var(--muted); letter-spacing: 0.02em;
  }
  .src:hover { color: var(--teal); text-decoration: none; }

  /* the redaction bar: a concealed stripe that lifts to a clear teal value */
  .val {
    flex: 1; min-width: 0; text-align: left;
    display: flex; align-items: center;
    height: 38px; padding: 0 12px; border: 0; border-radius: var(--radius-sm);
    cursor: pointer; color: var(--ink);
    background-color: color-mix(in srgb, var(--ink) 7%, transparent);
    background-image: repeating-linear-gradient(
      -45deg, transparent 0 6px,
      color-mix(in srgb, var(--ink) 5%, transparent) 6px 12px);
    transition: background .18s ease, color .18s ease, box-shadow .18s ease;
  }
  .val .txt {
    font-size: 0.9375rem; letter-spacing: 0.14em;
    overflow: hidden; text-overflow: ellipsis; white-space: nowrap;
  }
  .val:hover { background-color: color-mix(in srgb, var(--ink) 11%, transparent); }
  .val.on {
    color: var(--teal); background-image: none;
    background-color: var(--teal-wash);
    box-shadow: inset 0 -2px 0 var(--teal);
  }
  .val.on .txt { letter-spacing: 0.04em; }

  .acts { display: flex; gap: 5px; flex: none; }
  .ic {
    width: 36px; height: 36px; display: grid; place-items: center;
    border: 1px solid var(--line); border-radius: var(--radius-sm);
    background: var(--card); color: var(--muted); cursor: pointer;
    transition: border-color .15s ease, color .15s ease, background .15s ease;
  }
  .ic:hover { border-color: var(--teal); color: var(--teal); background: var(--teal-wash); }
  .ic:disabled { opacity: 0.5; cursor: default; }
  .ic.copy.done { border-color: var(--teal); color: var(--teal); background: var(--teal-wash); }
</style>
