// doc-catalog/web/src/lib/ReviewRow.svelte
<script>
  import { onMount } from 'svelte';
  import { revealField, confirmField, deleteField } from '$lib/api.js';
  import Icon from '$lib/Icon.svelte';

  // row: { id, entity_class, label, value_masked, score, title }
  // ondone: (id) => void  — parent removes the row after an action
  let { row, ondone } = $props();

  let shown = $state('');
  let revealed = $state(false);
  onMount(() => { shown = row.value_masked; });
  let editing = $state(false);
  let draft = $state('');
  let busy = $state(false);

  async function reveal() {
    if (revealed) return;
    shown = await revealField(row.id);
    revealed = true;
  }

  async function startEdit() {
    if (!revealed) await reveal();
    draft = shown;
    editing = true;
  }

  async function confirm() {
    busy = true;
    try {
      await confirmField(row.id, editing && draft.trim() ? { value: draft.trim() } : null);
      ondone?.(row.id);
    } finally { busy = false; }
  }

  async function reject() {
    busy = true;
    try { await deleteField(row.id); ondone?.(row.id); }
    finally { busy = false; }
  }
</script>

<div class="row">
  <div class="meta">
    <span class="label mono">{row.label}</span>
    <a class="src" href={`/doc/${row.document_id}`} title={row.title}>{row.title}</a>
  </div>

  <div class="val mono">
    {#if editing}
      <input class="mono" bind:value={draft} spellcheck="false" />
    {:else}
      <button class="reveal" class:on={revealed} onclick={reveal}
              title={revealed ? '' : 'Reveal to check'}>
        <Icon name={revealed ? 'eye-off' : 'eye'} size="14px" />
        <span class="txt">{shown}</span>
      </button>
    {/if}
  </div>

  <div class="acts">
    <button class="ic ok" onclick={confirm} disabled={busy} aria-label="Confirm">
      <Icon name="check" size="16px" />
    </button>
    <button class="ic" onclick={startEdit} disabled={busy} aria-label="Edit value">
      <Icon name="edit" size="15px" />
    </button>
    <button class="ic no" onclick={reject} disabled={busy} aria-label="Not a field / reject">
      <Icon name="x" size="16px" />
    </button>
  </div>
</div>

<style>
  .row {
    display: grid; grid-template-columns: 1fr 1.2fr auto; gap: var(--s-3); align-items: center;
    padding: var(--s-3) var(--s-4); border-top: 1px solid var(--line);
  }
  .row:first-child { border-top: 0; }
  .meta { display: flex; flex-direction: column; gap: 2px; min-width: 0; }
  .label { font-size: var(--t-cap); text-transform: uppercase; letter-spacing: 0.05em; color: var(--muted); }
  .src { font-size: var(--t-sm); color: var(--muted); overflow: hidden; text-overflow: ellipsis; white-space: nowrap; }
  .src:hover { color: var(--teal); }

  .val { min-width: 0; }
  .reveal {
    display: flex; align-items: center; gap: 8px;
    width: 100%; text-align: left; border: 0; cursor: pointer;
    background: color-mix(in srgb, var(--ink) 6%, transparent);
    border-radius: var(--radius-sm); padding: 7px 10px; color: var(--muted);
    letter-spacing: 0.1em; transition: background .15s ease, color .15s ease;
  }
  .reveal .txt { overflow: hidden; text-overflow: ellipsis; white-space: nowrap; }
  .reveal:hover { background: color-mix(in srgb, var(--ink) 9%, transparent); }
  .reveal.on {
    letter-spacing: 0.03em; color: var(--teal);
    background: var(--teal-wash);
  }
  input {
    width: 100%; padding: 7px 10px; border: 1px solid var(--teal);
    border-radius: var(--radius-sm); background: var(--card); color: var(--ink);
    box-sizing: border-box;
  }

  .acts { display: flex; gap: 5px; }
  .ic {
    width: 40px; height: 40px; display: grid; place-items: center;
    border: 1px solid var(--line); border-radius: var(--radius-sm);
    background: var(--card); color: var(--muted); cursor: pointer;
    transition: border-color .15s ease, color .15s ease, background .15s ease;
  }
  .ic:hover { border-color: var(--muted); }
  .ic.ok:hover { border-color: var(--teal); color: var(--teal); background: var(--teal-wash); }
  .ic.no:hover { border-color: var(--stamp); color: var(--stamp); background: var(--stamp-wash); }
  .ic:disabled { opacity: 0.5; cursor: default; }

  @media (max-width: 560px) {
    .row { grid-template-columns: 1fr; gap: var(--s-2); }
    .acts { justify-content: flex-end; }
  }
</style>

// doc-catalog/web/src/components/ReviewRow.tsx
import { useState } from "react";
import { Link } from "react-router-dom";
import { Eye, EyeOff, Check, Pencil, X } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { cn } from "@/lib/utils";
import { revealField, confirmField, deleteField } from "@/api";
import type { ReviewCandidate } from "@/api";

export function ReviewRow({ row, ondone }: { row: ReviewCandidate; ondone: (id: string) => void }) {
  const [shown, setShown] = useState(row.value_masked);
  const [revealed, setRevealed] = useState(false);
  const [editing, setEditing] = useState(false);
  const [draft, setDraft] = useState("");
  const [busy, setBusy] = useState(false);

  async function reveal() {
    if (revealed) return;
    setShown(await revealField(row.id));
    setRevealed(true);
  }

  async function startEdit() {
    if (!revealed) await reveal();
    setDraft(revealed ? shown : await revealField(row.id));
    setEditing(true);
  }

  async function confirm() {
    setBusy(true);
    try {
      await confirmField(row.id, editing && draft.trim() ? { value: draft.trim() } : null);
      ondone(row.id);
    } finally {
      setBusy(false);
    }
  }

  async function reject() {
    setBusy(true);
    try {
      await deleteField(row.id);
      ondone(row.id);
    } finally {
      setBusy(false);
    }
  }

  return (
    <div className="grid grid-cols-[1fr_1.2fr_auto] items-center gap-3 border-t px-4 py-3 first:border-t-0 max-[560px]:grid-cols-1 max-[560px]:gap-2">
      <div className="flex min-w-0 flex-col gap-0.5">
        <span className="text-xs uppercase tracking-wide text-muted-foreground">{row.label}</span>
        <Link
          to={`/doc/${row.document_id}`}
          title={row.title}
          className="truncate text-sm text-muted-foreground hover:text-accent"
        >
          {row.title}
        </Link>
      </div>

      <div className="min-w-0">
        {editing ? (
          <Input className="mono" value={draft} onChange={(e) => setDraft(e.target.value)} spellCheck={false} />
        ) : (
          <button
            type="button"
            onClick={reveal}
            title={revealed ? "" : "Reveal to check"}
            className={cn(
              "mono flex w-full items-center gap-2 rounded-md bg-foreground/[0.06] px-2.5 py-1.5 text-left tracking-[0.1em] text-muted-foreground transition-colors hover:bg-foreground/[0.09]",
              revealed && "bg-vault-wash tracking-[0.03em] text-vault",
            )}
          >
            {revealed ? <EyeOff className="size-3.5 flex-none" /> : <Eye className="size-3.5 flex-none" />}
            <span className="truncate">{shown}</span>
          </button>
        )}
      </div>

      <div className="flex justify-end gap-1.5 max-[560px]:justify-end">
        <Button
          variant="outline"
          size="icon"
          onClick={confirm}
          disabled={busy}
          aria-label="Confirm"
          className="hover:border-vault hover:bg-vault-wash hover:text-vault"
        >
          <Check />
        </Button>
        <Button variant="outline" size="icon" onClick={startEdit} disabled={busy} aria-label="Edit value">
          <Pencil />
        </Button>
        <Button
          variant="outline"
          size="icon"
          onClick={reject}
          disabled={busy}
          aria-label="Not a field / reject"
          className="hover:border-danger hover:bg-danger-wash hover:text-danger"
        >
          <X />
        </Button>
      </div>
    </div>
  );
}
